@startuml 6-1
actor ユーザ
boundary ブラウザ
control web.php as w
control Jissyu6_1Controller as c
entity Person as p
boundary index.blade.php as i
boundary show.blade.php as s

ユーザ -> ブラウザ : 該当ページをリクエスト[/jissyu13]
ブラウザ -> w : GET[/jissyu13]
w -> c :@index
c -> p : all()
p --> c
c -> i
ユーザ -> ブラウザ : 検索ボタンを押下
ブラウザ -> w : GET[/jissyu13/find]
w -> c : @find
c -> p : where()->first()
p --> c
c -> s 
@enduml